/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.car_rental_system;
import system_objects.inputValidator;
import system_objects.dataHandling;
import system_objects.user;
import system_objects.admin;
import java.awt.Color;
import java.util.*;

/**
 *
 * @author hasan
 */
public class Admin_Home extends javax.swing.JFrame {
    private admin admin = new admin();

    /**
     * Creates new form Admin_Home
     */
    public Admin_Home() {
        initComponents();
    }
    
    public Admin_Home(user info) {
        initComponents();
        this.admin.setID(info.getID());
        this.headerLbl.setText("Hey " + admin.getID().toUpperCase());
    }
    
    public Admin_Home(String id)
    {
        initComponents();
        this.admin.setID(id);
        this.headerLbl.setText("Hey " + admin.getID().toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idDialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        cusIDTxt = new javax.swing.JTextField();
        showBtn = new javax.swing.JButton();
        dialogWarningMessageLbl = new javax.swing.JLabel();
        bookingHistoryBtn = new javax.swing.JButton();
        headerLbl = new javax.swing.JLabel();
        addCarBtn = new javax.swing.JButton();
        generateReportBtn = new javax.swing.JButton();
        editCarBtn = new javax.swing.JButton();
        manageCustomerBtn = new javax.swing.JButton();
        collectPaymentBtn = new javax.swing.JButton();
        newAdminBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        changePassBtn = new javax.swing.JButton();
        changeNumberBtn = new javax.swing.JButton();
        warningMessageLbl = new javax.swing.JLabel();

        idDialog.setResizable(false);
        idDialog.setSize(new java.awt.Dimension(500, 300));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Enter the customer ID to view their booking history:");

        cusIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusIDTxtActionPerformed(evt);
            }
        });

        showBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showBtn.setText("Search");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });

        dialogWarningMessageLbl.setForeground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout idDialogLayout = new javax.swing.GroupLayout(idDialog.getContentPane());
        idDialog.getContentPane().setLayout(idDialogLayout);
        idDialogLayout.setHorizontalGroup(
            idDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idDialogLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idDialogLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(idDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dialogWarningMessageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(idDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cusIDTxt)
                        .addComponent(showBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                .addGap(95, 95, 95))
        );
        idDialogLayout.setVerticalGroup(
            idDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idDialogLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cusIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(showBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dialogWarningMessageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        bookingHistoryBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bookingHistoryBtn.setText("Booking History");
        bookingHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingHistoryBtnActionPerformed(evt);
            }
        });

        headerLbl.setFont(new java.awt.Font("Segoe UI Black", 2, 36)); // NOI18N

        addCarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCarBtn.setText("Add Car");
        addCarBtn.setName("addCar"); // NOI18N
        addCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarBtnActionPerformed(evt);
            }
        });

        generateReportBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        generateReportBtn.setText("Generate Report");
        generateReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateReportBtnActionPerformed(evt);
            }
        });

        editCarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editCarBtn.setText("Edit Car Info");
        editCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCarBtnActionPerformed(evt);
            }
        });

        manageCustomerBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        manageCustomerBtn.setText("Manage Customers");
        manageCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerBtnActionPerformed(evt);
            }
        });

        collectPaymentBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        collectPaymentBtn.setText("Payment Collection");
        collectPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collectPaymentBtnActionPerformed(evt);
            }
        });

        newAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newAdminBtn.setText("Add New Admin");
        newAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAdminBtnActionPerformed(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        changePassBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changePassBtn.setText("Change Password");
        changePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassBtnActionPerformed(evt);
            }
        });

        changeNumberBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changeNumberBtn.setText("Change Phone Number");
        changeNumberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeNumberBtnActionPerformed(evt);
            }
        });

        warningMessageLbl.setForeground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(addCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(editCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(changePassBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(headerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warningMessageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bookingHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(generateReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(139, 139, 139)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(collectPaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(manageCustomerBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(110, 110, 110)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changeNumberBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(newAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(headerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(changeNumberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collectPaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(warningMessageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        addCarBtn.getAccessibleContext().setAccessibleName("addCar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookingHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingHistoryBtnActionPerformed
        this.idDialog.setVisible(true);
    }//GEN-LAST:event_bookingHistoryBtnActionPerformed

    private void addCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarBtnActionPerformed
        new Add_Car().setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_addCarBtnActionPerformed

    private void generateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateReportBtnActionPerformed
        new Report().setVisible(true);
    }//GEN-LAST:event_generateReportBtnActionPerformed

    private void editCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCarBtnActionPerformed
        new Edit_Car_Info().setVisible(true);
    }//GEN-LAST:event_editCarBtnActionPerformed

    private void manageCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerBtnActionPerformed
        new Manage_Customers().setVisible(true);
    }//GEN-LAST:event_manageCustomerBtnActionPerformed

    private void collectPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collectPaymentBtnActionPerformed
        new Payment_Collection().setVisible(true);
    }//GEN-LAST:event_collectPaymentBtnActionPerformed

    private void newAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAdminBtnActionPerformed
        Register_User register = new Register_User(this.admin.getID());
        register.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newAdminBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void changePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassBtnActionPerformed
        new Change_Password(this.admin.getID(), "Admin").setVisible(true);
    }//GEN-LAST:event_changePassBtnActionPerformed

    private void changeNumberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeNumberBtnActionPerformed
        new Change_Number(this.admin.getID(), "Admin").setVisible(true);
    }//GEN-LAST:event_changeNumberBtnActionPerformed

    private void cusIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusIDTxtActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        dataHandling files = new dataHandling();
        user user = new user();
        inputValidator validate = new inputValidator();
        ArrayList<String[]> customers = files.ReadFromFile("Customer.txt");
        
        if(!validate.isNullorEmpty(this.cusIDTxt.getText()))
        {
            String[][] customer = user.searchForRecord(customers, this.cusIDTxt.getText());
                      
            if(validate.isNullorEmpty(customer[0][0])){
                this.idDialog.setVisible(false);
                this.warningMessageLbl.setText("Car is not found !");
            }
            else{
                this.idDialog.setVisible(false);
                this.warningMessageLbl.setText("");
                this.cusIDTxt.setText("");
                new Booking_History(customer[0][0], false).setVisible(true);
            }
        }
        else
            this.dialogWarningMessageLbl.setText("Input a valid customer ID !");
    }//GEN-LAST:event_showBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarBtn;
    private javax.swing.JButton bookingHistoryBtn;
    private javax.swing.JButton changeNumberBtn;
    private javax.swing.JButton changePassBtn;
    private javax.swing.JButton collectPaymentBtn;
    private javax.swing.JTextField cusIDTxt;
    private javax.swing.JLabel dialogWarningMessageLbl;
    private javax.swing.JButton editCarBtn;
    private javax.swing.JButton generateReportBtn;
    private javax.swing.JLabel headerLbl;
    private javax.swing.JDialog idDialog;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton manageCustomerBtn;
    private javax.swing.JButton newAdminBtn;
    private javax.swing.JButton showBtn;
    private javax.swing.JLabel warningMessageLbl;
    // End of variables declaration//GEN-END:variables
}
